spring:
  datasource:
    url: ${POSTGRES_DB_URL}
    username: ${POSTGRES_DB_USER}
    password: ${POSTGRES_DB_PASSWORD}

  jpa:
    hibernate.ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

  config:
    import: optional:file:.env[.properties]