CREATE TABLE short_url (
    id BIGSERIAL PRIMARY KEY NOT NULL,
    short_code VARCHAR(10) UNIQUE,
    original_url TEXT NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);